In [1]:
import os
from dotenv import load_dotenv
from googleapiclient.discovery import build
#charger la clé sans l'écrire en dur
load_dotenv()
API_KEY = os.getenv('YOUTUBE_API_KEY')
youtube = build('youtube', 'v3', developerKey=API_KEY)

La porte d'entrée de votre pipeline ETL (Extract, Transform, Load). Son rôle est d'aller chercher (Extract) des informations structurées sur les serveurs de YouTube

In [ ]:
def get_channel_playlists(channel_id):
    playlists = []
    next_page_token = None

    while True:
        request = youtube.playlists().list(
            part="snippet,contentDetails",
            channelId=channel_id,
            maxResults=50,
            pageToken=next_page_token
        )
        response = request.execute()

        for item in response['items']:
            playlists.append({
                'title': item['snippet']['title'],
                'playlist_id': item['id'],
                'video_count': item['contentDetails']['itemCount']
            })

        next_page_token = response.get('nextPageToken')
        if not next_page_token:
            break
            
    return playlists

# ID de la chaîne Huberman Lab (trouvé dans l'URL de sa chaîne)
HUBERMAN_CHANNEL_ID = "UC2D2CMWXMOVWx7giW1n3LIg"

# Exécution
try:
    all_playlists = get_channel_playlists(HUBERMAN_CHANNEL_ID)
    print(f"✅ {len(all_playlists)} playlists trouvées pour Huberman Lab.\n")
    
    for pl in all_playlists:
        print(f"Titre: {pl['title']}")
        print(f"ID: {pl['playlist_id']}")
        print(f"Nombre de vidéos: {pl['video_count']}")
        print("-" * 30)
except Exception as e:
    print(f"❌ Erreur : {e}")

❌ Erreur : name 'youtube' is not defined

:

In [3]:
def get_only_playlist_ids(channel_id):
    # On ne demande que 'id' dans le paramètre 'part' pour être plus léger
    response = youtube.playlists().list(
        part="id",
        channelId=channel_id,
        maxResults=50
    ).execute()

    # On extrait uniquement l'identifiant 'id' de chaque élément
    return [item['id'] for item in response.get('items', [])]

# --- TEST ---
HUBERMAN_ID = "UC2D2CMWXMOVWx7giW1n3LIg"
playlist_ids = get_only_playlist_ids(HUBERMAN_ID)

print(playlist_ids)

['PLPNW_gerXa4M58QbO_KM4aMLmSINuywh3', 'PLPNW_gerXa4PSUFzfPS0rCNzuw5eFSEQE', 'PLPNW_gerXa4Me2riDZ14b_mMhJ4Uszifu', 'PLPNW_gerXa4NlSlWv4KcTJZouYs_WbmQS', 'PLPNW_gerXa4OwtESKVrZF3PSnrNit4ngb', 'PLPNW_gerXa4OGNy1yE-W9IX-tPu-tJa7S', 'PLPNW_gerXa4OoypUEgZI7uouI12WZrxeS', 'PLPNW_gerXa4MFy52YhdZJYhOk11KdfG9G', 'PLPNW_gerXa4NKRk-x4U-Cuza8FPV8dx5x', 'PLPNW_gerXa4M9RzC_aqEVT3yeiJMdrazo', 'PLPNW_gerXa4MgnHtb1c65IoKEctR_eZPJ', 'PLPNW_gerXa4PTAbCaMIfN9BkYNdoDhFEP', 'PLPNW_gerXa4O24l7ZHoJbMC2xOO7SpS7K', 'PLPNW_gerXa4Nt_vwLUY6Nl1oG0UfsW5VM', 'PLPNW_gerXa4PKMqne6CTj7tWvUvObWA3s', 'PLPNW_gerXa4NDL0b7CeID7wf1GYUjz594', 'PLPNW_gerXa4N_PVVoq0Za03YKASSGCazr', 'PLPNW_gerXa4Pdodlfly8mMdotUJ-C6NnJ', 'PLPNW_gerXa4Oge1tYt2NxOD23eMnUJxkO', 'PLPNW_gerXa4NTotATnGIgwplXRzuJtYbY', 'PLPNW_gerXa4Pc8S2qoUQc5e8Ir97RLuVW', 'PLPNW_gerXa4NjSNbZhpSDLXDHukNcp0JZ']

In [4]:
def get_channel_id(handle):
    # Prépare la requête pour chercher une chaîne par son "handle" (@nom)
    request = youtube.channels().list(
        part="id",           # On demande uniquement l'ID technique
        forHandle="hubermanlab"   # On donne le nom de la chaîne (ex: "hubermanlab")
    )
    # Envoie la requête à Google et récupère la réponse brute
    response = request.execute()
    
    # Extrait l'ID du premier résultat trouvé dans la liste 'items'
    return response['items'][0]['id']

# Utilisation
nom_chaine = "hubermanlab"
id_general = get_channel_id(nom_chaine)
print(f"ID de la chaîne : {id_general}")

ID de la chaîne : UC2D2CMWXMOVWx7giW1n3LIg

In [5]:
def get_playlist_ids(channel_id):
    # Prépare la liste des playlists rattachées à cet ID de chaîne
    request = youtube.playlists().list(
        part="id",           # On ne veut que les IDs techniques (PL...)
        channelId=channel_id,# On précise de quelle chaîne on parle
        maxResults=50        # On récupère jusqu'à 50 playlists d'un coup
    )
    # Exécution de l'appel API
    response = request.execute()
    
    # Compréhension de liste : on crée une liste propre avec juste les IDs
    return [item['id'] for item in response.get('items', [])]

# Utilisation
liste_des_playlists = get_playlist_ids(id_general)
print(f"Liste des IDs : {liste_des_playlists}")

Liste des IDs : ['PLPNW_gerXa4M58QbO_KM4aMLmSINuywh3', 'PLPNW_gerXa4PSUFzfPS0rCNzuw5eFSEQE', 'PLPNW_gerXa4Me2riDZ14b_mMhJ4Uszifu', 'PLPNW_gerXa4NlSlWv4KcTJZouYs_WbmQS', 'PLPNW_gerXa4OwtESKVrZF3PSnrNit4ngb', 'PLPNW_gerXa4OGNy1yE-W9IX-tPu-tJa7S', 'PLPNW_gerXa4OoypUEgZI7uouI12WZrxeS', 'PLPNW_gerXa4MFy52YhdZJYhOk11KdfG9G', 'PLPNW_gerXa4NKRk-x4U-Cuza8FPV8dx5x', 'PLPNW_gerXa4M9RzC_aqEVT3yeiJMdrazo', 'PLPNW_gerXa4MgnHtb1c65IoKEctR_eZPJ', 'PLPNW_gerXa4PTAbCaMIfN9BkYNdoDhFEP', 'PLPNW_gerXa4O24l7ZHoJbMC2xOO7SpS7K', 'PLPNW_gerXa4Nt_vwLUY6Nl1oG0UfsW5VM', 'PLPNW_gerXa4PKMqne6CTj7tWvUvObWA3s', 'PLPNW_gerXa4NDL0b7CeID7wf1GYUjz594', 'PLPNW_gerXa4N_PVVoq0Za03YKASSGCazr', 'PLPNW_gerXa4Pdodlfly8mMdotUJ-C6NnJ', 'PLPNW_gerXa4Oge1tYt2NxOD23eMnUJxkO', 'PLPNW_gerXa4NTotATnGIgwplXRzuJtYbY', 'PLPNW_gerXa4Pc8S2qoUQc5e8Ir97RLuVW', 'PLPNW_gerXa4NjSNbZhpSDLXDHukNcp0JZ']

In [6]:
import requests

In [7]:
URL = 'https://youtube.googleapis.com/youtube/v3/channels?part=contentDetails&forHandle=hubermanlab&key=AIzaSyD1kBt4QWzpcRQpU-5VuEikhrwvrHu2axk'

In [8]:
response = requests.get(URL)
response

In [9]:
res = response.json()
res

{'kind': 'youtube#channelListResponse',
 'etag': 'o7mhzceg67XbnpCxMPdm2ZA6N9M',
 'pageInfo': {'totalResults': 1, 'resultsPerPage': 5},
 'items': [{'kind': 'youtube#channel',
   'etag': '-El_jAIQLAlD5hyg1aeoQW7M538',
   'id': 'UC2D2CMWXMOVWx7giW1n3LIg',
   'contentDetails': {'relatedPlaylists': {'likes': '',
     'uploads': 'UU2D2CMWXMOVWx7giW1n3LIg'}}}]}

In [10]:
res['items'][0]['contentDetails']['relatedPlaylists']['uploads']

'UU2D2CMWXMOVWx7giW1n3LIg'

In [11]:
URL = 'https://youtube.googleapis.com/youtube/v3/channels?part=contentDetails&forHandle=hubermanlab&key=AIzaSyD1kBt4QWzpcRQpU-5VuEikhrwvrHu2axk'
response = requests.get(URL)
response
res = response.json()
listId = []
res = response.json()

In [12]:
# 1. On définit l'ID de la playlist récupéré juste avant
playlist_id_uploads = 'UU2D2CMWXMOVWx7giW1n3LIg'

# 2. URL pour lister les éléments de la playlist
# On demande le snippet (pour le titre) et le contentDetails (pour l'ID vidéo)
url_playlist = f"https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId={playlist_id_uploads}&maxResults=50&key={API_KEY}"

response_pl = requests.get(url_playlist)
data = response_pl.json()

# 3. Extraction des Video IDs du premier lot (50 premières vidéos)
video_ids = [item['contentDetails']['videoId'] 
for item in data['items']]

print(f"Nombre de vidéos récupérées : {len(video_ids)}")
print(f"Exemple d'IDs : {video_ids[:]}")

Nombre de vidéos récupérées : 50
Exemple d'IDs : ['sQcS6f2qYoQ', '3bnLgOxHMB8', 'FBgM7jndkLQ', 'U6dnOVth7-I', 'RTPNJgHeZBI', 'xZ4I2aE8zQA', 'Tmw2dW0a9DY', '0VSOoMuStvg', '6-mEiwe2NhE', 'hnzrPKvRBD8', 'C0DMdUqF73Q', 'RECLTp_YxSU', 'hlOA8ObQJXo', 'iuPQmw4Ax00', 'u4VTFb4awrQ', 'cru_4P6qVYQ', '9G2MRFs4vac', '7UeojKTzeHE', 'Ew0-Lg_Evj0', '9GzlbLIU5dU', '_Q4XT82yd-Q', 'NEkUNahduWY', 'CH9hcEh1Lv4', 'rAbJC-Qaw7Q', 'JsICN9ZiSjA', 'VPi_eWiaqdg', 'BRG4_KfTxbs', 'lEULFeUVYf0', 'iNL_BFlHYZ8', 'zF9lcau3_to', 'gkWk11WKeVc', 'qzXU390N3vs', 'RmwbNdyrilk', 't6RCTP4fc9Q', '23t_ynq2tmk', 'QwK8ChEcV2Q', 'jFXTc_rCTj4', 'bdsc3Spm6Sw', 'fh2dBmLN-ZM', '9tgelcI5X2Q', 'D1wxOiVXM_w', 'qGb7hYMlA3o', 'oDRffy7sTBU', 'fYhY-vC000A', '2g_wpjzC_-c', 'zHyvVajsqMw', 'zYuw-8pwnp8', 'nMkQUlBtFlk', 'n_MVhE63ZQQ', 'itDBS3zefuI']

In [13]:
all_video_ids = []
next_page_token = None

# La boucle continue tant qu'il y a un jeton "page suivante"
while True:
    # On ajoute le paramètre pageToken à l'URL
    url = f"https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails&playlistId={playlist_id_uploads}&maxResults=50&pageToken={next_page_token if next_page_token else ''}&key={API_KEY}"
    
    response = requests.get(url).json()
    
    # Extraction des IDs de la page actuelle
    video_ids_page = [item['contentDetails']['videoId'] for item in response.get('items', [])]
    all_video_ids.extend(video_ids_page)
    
    # On récupère le jeton pour la page suivante
    next_page_token = response.get('nextPageToken')
    
    # S'il n'y a plus de jeton, on s'arrête
    if not next_page_token:
        break

print(f"✅ Extraction terminée ! Nombre total de vidéos récupérées : {len(all_video_ids)}")

✅ Extraction terminée ! Nombre total de vidéos récupérées : 481

In [14]:
all_video_ids = []
token = "" # On commence avec un texte vide

while True:
    # On ajoute le token à la fin de l'URL
    url = f"https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails&playlistId={playlist_id_uploads}&maxResults=50&key={API_KEY}&pageToken={token}"
    
    response = requests.get(url).json()
    
    # 1. On récupère les items de la page actuelle
    items = response.get('items', [])
    
    # 2. On extrait les IDs et on les ajoute à notre liste générale
    for item in items:
        v_id = item['contentDetails']['videoId']
        all_video_ids.append(v_id)
    
    # 3. On cherche le token de la page suivante
    token = response.get('nextPageToken')
    
    # 4. Si pas de token, on a fini toutes les pages !
    if not token:
        break

# --- AFFICHAGE POUR VÉRIFIER ---
print(f"✅ Total : {len(all_video_ids)} vidéos trouvées.")
print(f"Voici les premiers IDs : {all_video_ids[:]}")

✅ Total : 481 vidéos trouvées.
Voici les premiers IDs : ['sQcS6f2qYoQ', '3bnLgOxHMB8', 'FBgM7jndkLQ', 'U6dnOVth7-I', 'RTPNJgHeZBI', 'xZ4I2aE8zQA', 'Tmw2dW0a9DY', '0VSOoMuStvg', '6-mEiwe2NhE', 'hnzrPKvRBD8', 'C0DMdUqF73Q', 'RECLTp_YxSU', 'hlOA8ObQJXo', 'iuPQmw4Ax00', 'u4VTFb4awrQ', 'cru_4P6qVYQ', '9G2MRFs4vac', '7UeojKTzeHE', 'Ew0-Lg_Evj0', '9GzlbLIU5dU', '_Q4XT82yd-Q', 'NEkUNahduWY', 'CH9hcEh1Lv4', 'rAbJC-Qaw7Q', 'JsICN9ZiSjA', 'VPi_eWiaqdg', 'BRG4_KfTxbs', 'lEULFeUVYf0', 'iNL_BFlHYZ8', 'zF9lcau3_to', 'gkWk11WKeVc', 'qzXU390N3vs', 'RmwbNdyrilk', 't6RCTP4fc9Q', '23t_ynq2tmk', 'QwK8ChEcV2Q', 'jFXTc_rCTj4', 'bdsc3Spm6Sw', 'fh2dBmLN-ZM', '9tgelcI5X2Q', 'D1wxOiVXM_w', 'qGb7hYMlA3o', 'oDRffy7sTBU', 'fYhY-vC000A', '2g_wpjzC_-c', 'zHyvVajsqMw', 'zYuw-8pwnp8', 'nMkQUlBtFlk', 'n_MVhE63ZQQ', 'itDBS3zefuI', 'VnPQ4mLRG-c', 'vXVGAanRWQM', 'HXuj7wAt7u8', 'eRx6rcJefVI', 'iT8W6kaD-RA', 'SOo4yNoaAoc', 'c-35hs95O18', 'hMzfGZnaPN8', '25PtptE7mWk', 'AXug0tXxbI0', 'yGC6T-olRQk', 'ZtTUfMHuioA', 'Y3NUEPNZDMA', 'tb6ApBIXr1k', 'tpntW9Tte4M', 'PCbD3hFyfCk', 'Ykvkg2Jz3X8', 'KBkl3I645c8', 'yc6wutvd0wQ', '9gJLWk3W5GQ', '-VLr4aqmWio', 'ADzehrUgzGg', 'cpKsogGdem4', '-zI0ZgKM0xA', 'zP3vh_uoCno', 'xGmGBFpmdhQ', '7mDA3OzeHgg', 'vXTK0Ac9i1Q', 'WwRc2SEo-VI', 'VqiPNN4Jblk', '0UyOAtjKXpM', 'MlmFj1-mOtg', 'pN1UL1M9sqc', 'JgOx50_ogJw', '7SIjcX5B1Vs', 'dy_iLCJggO0', '2t4vswC-3mY', '8qPGUi4XSU0', 'cIla9axQRyM', 'cjAvD-U5so0', 'alVWRl_X_AA', '4TsOnsPDKKY', 'D61jJJPIQeo', 'Whe2Jh9q6jI', '2XMb3MD6g6Q', 'H4mMZ0vliMo', 'XeN6eGO6FVQ', 'rcAyjg-oy84', 'bmFw2kQ9pRs', 'aZklQpFa2kE', 'oeVfCqlHn_I', 'Ibj1k3IZTNU', 'LAwBdRR4wQk', 'k8SBJzsIWAo', 'OvHbhzArbfE', 'gyE6Z4GLEeM', 'mJv1_esiJ8g', 'ewnvjnuFTOY', 'qP4RESPJ8vo', 'gZGz0SS7KCE', 'R2SfjPSaphk', 'DLdLK1pfvaQ', 'WxtxzRdJFTI', 'h_1zlead9ZU', 'HWcphoKlbxY', 'zqANjUGarAw', 'i4gvIeA3RcI', 'CLbVW3Pj46A', 'vm1GbSPx48g', 'SsKkZTjUJEk', 'JaRGJVrJBQ8', '2Y_PxTxLFVg', '2ZkJtIouKzE', 'inUkNZe5H3k', 'Eb5UYEQDBJg', 'SCzecagKBjY', 'zprh05F_ius', '5wjmlhII1I8', 'ijdpvG24IkE', 'Pmd6knanPKw', 'HTJ8lDtJOg4', 'RSnol_TVrzQ', '9vQZT2igXN4', 'fSBgDq2ttCw', '1e4QdH-LeKc', 'zpkwefXtbfk', 'v2YTJBKLLY0', '_eDg9yOvvrQ', 'UpRsmu9xfJA', '6ck9fa6_C8c', 'q-wRvsiGYIs', 'ssmwxKPFMFU', 'J7yn4tJEmJU', '7MEhDlw1e9k', 'UyneMnERmnI', 'Rk02H9r_E4A', 'jgaoLdS82vw', 'lYK4UFf8mlc', 'f4cdu-QiKHo', 'e7Dxyc5w3hU', 'hCyvqRq5YmM', 'VnEy78RL2YY', '_oOEKKiwdDE', '5--yogtN6oM', 'U3cSnzdyyXU', 'wFucddupQlk', 'ZizbA-MtjAs', 'NtQ-kdLlQiU', 'Nmo4bxfFzM0', 'p6zNt7HUCrY', 'KuuoLT-fq4s', 'Vh97z1ephuc', 'goCbY3zIZKo', 'c9JmHOUp6VU', 'Ag_a3VAQlgk', 'N5DAW8mkJ6Y', 'hviHgpxjXcc', 'rkFHdXo1O0w', 'v4HRWgwjP_k', 'bAWUYuygS_U', 'FCFQx3cA0Lg', 'Z3OpxT65fKw', 'qdk7XuBgSjw', 'QYAgf_lfio4', '_2u_FiHTuvQ', 'OLQRAMZi--c', 'wAnDWfEIwoE', 'Q4qWzbP0q7I', '8tkQDgUdpLs', 'Kyud5aFGjHU', '3-ukCGQJk2c', 'Uv-O7SZQ1H4', 'qUz93CyNIz0', 'qi4VwpEs3LE', '7aj00T-TKDc', 'SjPJn4QP0dk', '2PgNi03lLc0', '5Gg_uZIumtE', 'J2oqi41dCNc', 'D97TQuy946k', 'yRSBl2ovMz4', 'K0hkhbGYaGQ', 'nyxlCNcvaLA', 'jwChiek_aRY', 'Phm-Alz1Zjo', '4AwyVTHEU3s', '6YLdlK2hYnw', 'tR73Ny4Dt9s', 'hF32FvBH4gI', '8N7mdkrXgbc', 'JnlSDaBjCCU', 'In9Bq4EJMZw', '1SXDXdngX2M', 'z5W74QC3v2I', 'q-H_A_dQUxQ', '6RZbGrq9BxE', 'Og56hmAspV8', 'lIo9FcrljDk', 'etbfLTHD_VU', 'bGixnNGvSkg', 'HiyzzcuaAac', 'rZkMpVLcVsg', 'i5611OvTFGM', 'SuR0DaYoe0Y', 'vfRtLI6cJrk', 'kgr22uMsJ5o', 'wRsX_ZkzxvQ', 'jC8Pu9HBd48', '4RFEkGKKhdE', 'ajneRM-ET1Q', 'FOi5s3OUogo', 'QbMxDZeB8Ks', 'i_DEPeCKxs8', 'kG5Qb9sr0YQ', '62lVH-6xYGY', 'U2BPitASUh0', 'ddq8JIMhz7c', 'wgUjIRtote8', 'P0hO6jPjFRM', 'CD0bRU1e1ZM', '5tYR7e5Wpyc', 'nOgypsWKjm4', 'Ov4yyK15-K8', 'Gf-kC30SLtc', '79p1X_7rAMo', 'pZX8ikmWvEU', 'mAlt_HKX4as', '0Dtt95_xabw', 'jouFvyRZntk', '1CxJVdeyltw', '7TkGDj4LaOU', 'WFcYF_pxLgA', 'C5KpIXjpzdY', 'G1VUSu6sGoU', 'csubiPlvFWk', '-e9ErUozQo4', '6P8hrzjnetU', 'XY0rBdaDXD8', 'bUr_9fgfnto', 'SZSRgyl7pyQ', 'nqNEtdHVUjM', 'yOoVz9E9kfQ', 'SyWC8ZFVxGo', 'Jy4rJcYmtUM', '8qaBpM73NSk', 'S_SrHS8FvMM', 'jGZ1mR9uLU0', 'PVmQOLYckKQ', 'F9KrZd_-ge0', 'C3X0bUAiluE', 'xX6hiEmDmxs', 'zlc4VrDx_qk', 'tcueMCe-0zo', 'GA89kjVY6Ik', '4F_RBc1akC8', 'etEJrznE-c0', 'Ky-ZJ9SS-x4', 'FLxIoNguGRU', 'hvPGfcAgk9Y', 'acgz0C-z-gc', '-OBCwiPPfEU', 'zU5EYw06wtw', 'kpTJqwIfHcM', 'ttNxNbqNQK4', 'oL3SkPV1_Ik', 'p4ZfkezDTXQ', 'gdUNjPijwA8', 'gE0_8AjTFaM', 'XT_6Lvkhxvo', 'HYVeP4F0GNU', 'QpoaNklmRPc', 'zVCaYyUWWSw', 'V0Sdgn0_kFM', 'j2sMqSDLd4k', 'CQlTmOFM4Qs', 'TG8VM5-CTfw', 'K9lORz2_XSU', 'CuzL1qxUyHw', 'CVh3_8e5u8I', 'AtChcxeaukQ', 'nDLb8_wgX50', 'zbpb1wd-wvs', 'GpgqXCkRO-w', 'n28W4AmvMDE', 'LRM5LutB538', 'ccrbE0QHy94', '50BZQRT1dAg', 'xTtM2AvCRyA', 'wG3UFHR1o48', '3gtvNYa3Nd8', 'wAZn9dF3XTo', 'eC9fiJBdMG0', 'W5zqC5cYcS0', 'EhlIkzJwPlk', 'pkJi9Raxikg', 'qJ3uV7coZbA', 'CJIXbibQ0jI', '1Wo6SqLNmLk', 'FeRgqJVALMQ', 'cwakOgHIT0E', 'q8CHXefn7B4', '7Ey_vTTgJGc', 'yOJvm_ri_hk', 'qNzl12g0Dd8', 'eMqWH3LYiII', 'gveDhZW-rUk', 'qPKd99Pa2iU', 'z8c6EyMNd0A', 'tLRCS48Ens4', 'yixIc1Ai6jM', 'eJU6Df_ffAE', '29n0WG317tM', 'F54qXuTpgfM', 'Rxmv7rT9leo', 'VOfwbcveP84', 'HoH93judXmE', 'X8Hw8zeCDTA', 'aQDOU3hPci0', 'RI112zW8GDw', 'LYYyQcAJZfk', '_ltcLEM-5HU', 'FE0lTEUa7EY', 'doupx8SAs5Y', 'slUCmZJDXrk', 'S8jWFcDGz4Y', 'dicP_kA-RA0', 'sxgCC4H1dl8', 'fcxjwA4C4Cw', 'x3MgDtZovks', 'eIxVfln02Ss', 'cS7cNaBrkxo', 'uWV9a3zEaL4', '0RYyQRQFgFk', '3ZGItIAUQmI', '6ZrlsVx85ek', 'ulHrUVV3Kq4', 'K-TW2Chpz4k', 'cp9GXl9Qk_s', 'ufsIA5NARIo', '7R3-3HR6-u4', 'at37Y8rKDlA', 'CDUetQMKM6g', 'S8nPJU9xkNw', 'q37ARYnRDGc', 'x4m_PdFbu-s', 'juD99_sPWGU', 'BMTt8gSl13s', 'UIy-WQCZd4M', 'CGjdgy0cwGk', 'oNkDA2F7CjM', 'GVRDGQhoEYQ', 'CyDLbrZK75U', 'O1YRwWmue4Y', 'zEYE-vcVKy8', 'ycOBZZeVeAc', 'uak_dXHh6s4', 'tLS6t3FVOTI', '-wIt_WsJGfw', '__RAXBLt1iM', 'KPlJcD-o-4Q', 'uwWOc_RqTBA', 'O640yAgq5f8', 'vZ4kOr38JhY', 'iw97uvIge7c', '6I5I56uVvLw', 'xjEFo3a1AnI', 'LTGGyQS1fZE', 'TO0WUTq5zYI', 'K4Ze-Sp6aUE', 'lsODSDmY4CY', 'wTBSGgbIvsY', 'Z7MU6zrAXsM', 'q1Ss8sTbFBY', 'X4QE6t-MkYE', 'gXvuJu1kt48', 'Nr5xb-QCBGA', 'uXs-zPc63kM', 'uxZFl4BDOGk', 'yb5zpo5WDG4', '3_auLYOilb8', 'LVxL_p_kToc', 'DkS1pkKpILY', '2Ds1m5gflCI', 'DTCmprPCDqc', 'h2aWYjSA1Jc', '7YGZZcXqKxE', 'm_OazsImOiI', 'UChhXiFPRgg', 'T65RDBiB5Hs', 'UNCwdFxPtE8', 'OadokY8fcAA', 'a9yFKPmPZ90', 'tkH2-_jMCSk', 'IOl28gj_RXw', 'dzOvi0Aa2EA', '099hgtRoUZw', 'szqPAPKE5tQ', 'RBK5KLA5Jjg', 'XcvhERcZpWw', 'EQ3GjpGq5Y8', 'UF0nqolsNZc', 'ncSoor2Iw8k', 'pq6WHJzOkno', 'IAnhFUUCq6c', 'VAEzZeaV5zM', 'azb3Ih68awQ', 'ouCWNRvPk20', '15R2pMqU2ok', 'PctD-ki8dCc', 'gMRph_BvHB4', 'BwyZIWeBpRw', 'Ze2pc6NwsHQ', 'dFR_wFN23ZY', 't1F7EEGPQwo', 'GLgKkG44MGo', 'Wcs2PFz5q6g', 'n9IxomBusuw', 'RgAcOqVRfYA', 'oC3fhUjg30E', '31wjVhCcI5Y', 'HXzTbCEqCJc', 'KVjfFN89qvQ', '8IWDAqodDas', 'iMvtHqLmEkI', 'poOf8b2WE2g', 'oUu3f0ETMJQ', 'E7W4OQfJWdw', '9tRohh0gErM', '77CdVSpnUX4', 'QmOF0crdyRU', 'GzvzWO0NU50', 'hFL6qRIJZ_Y', '2XGREPnlI8U', 'DtmwtjOoSYU', 'Xu1FMCxoEFc', 'p3JLaF_4Tz8', 'xmhsWAqP_0Y', 'gbQFSMayJxk', 'rW9QKc-iFoY', 'VRvn3Oj5r3E', 'aXvDEmo6uS4', 'JVRyzYB9JSY', 'w9MXqXBZy9U', 'Mwz8JprPeMc', 'ObtW353d5i0', 'VQLU7gpk_X8', 'XLr2RKoD-oY', 'GqPGXG5TlZw', 'xJ0IBzCjEPk', 'xaE9XyMMAHY', 'JPX8g8ibKFc', 'x7qbJeRxWGw', '17O5mgXZ9ZU', 'qJXKhu5UZwk', 'rBdhqBGqiMc', 'J7SrAEacyf8', 'hcuMLQVAgEg', 'PZ-GvIOhcf8', 'vA50EK70whE', 'XfURDjegrAw', 'ntfcfJ28eiU', 'mcPSRWUYCv0', 'uuP-1ioh4LY', 'hx3U64IXFOY', 'LG53Vxum0as', 'FFwA0QFmpQ4', 'NAATB55oxeQ', 'nwSkFq4tyC0', 'nm1TxQj9IsQ', 'H-XfCl-HpRM', '4b6bwcWK6GE']

In [15]:
# 1. On prépare la liste pour stocker les résultats
resultats = []

# 2. Boucle de batching (on avance de 50 en 50)
for i in range(0, len(video_ids), 50):
    # On transforme le lot d'IDs en texte séparé par des virgules
    ids_batch = ",".join(video_ids[i:i+50])
    
    # Appel à l'API
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={ids_batch}&key={API_KEY}"
    response = requests.get(url).json()
    
    # 3. On extrait les infos de chaque vidéo du lot
    for item in response.get('items', []):
        resultats.append({
            'Titre': item['snippet']['title'],
            'Vues': item['statistics'].get('viewCount', 0),
            'Likes': item['statistics'].get('likeCount', 0),
            'Date': item['snippet']['publishedAt']
        })

# Affichage du premier résultat pour vérifier
print(resultats[0])

{'Titre': 'Male Roles, Obligations and Options for Building a Fulfilling Life | Scott Galloway', 'Vues': '66194', 'Likes': '2094', 'Date': '2026-04-27T12:01:38Z'}

In [16]:

import pandas as pd
infos_videos_completes = []

# 2. On traite les IDs par groupes de 50 (le maximum autorisé)
for i in range(0, len(all_video_ids), 50):
    
    # On prend un groupe de 50 IDs et on les transforme en une ligne de texte
    groupe_ids = ",".join(all_video_ids[i:i+50])
    
    # On demande les détails (Titre, Vues, Likes, Date) à Google pour ce groupe
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={groupe_ids}&key={API_KEY}"
    reponse = requests.get(url).json()
    
    # 3. Pour chaque vidéo du groupe, on range les infos proprement
    for video in reponse.get('items', []):
        infos_videos_completes.append({
            'Titre': video['snippet']['title'],
            'Vues': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Date': video['snippet']['publishedAt']
        })

# --- VÉRIFICATION FINALE ---

print(f"Nous avons récupéré les détails de {len(infos_videos_completes)} vidéos.")
df = pd.DataFrame(infos_videos_completes)

# 2. On nettoie la date pour qu'elle soit plus facile à lire (ex: 2024-03-28)
df['Date'] = pd.to_datetime(df['Date']).dt.date

# 3. On affiche le tableau final
print("Tableau de bord des vidéos :")
display(df)

Nous avons récupéré les détails de 481 vidéos.
Tableau de bord des vidéos :

,Titre,Vues,Likes,Date
0,"Male Roles, Obligations and Options for Buildi...",66194,2094,2026-04-27
1,"Essentials: The Neuroscience of Speech, Langua...",33783,709,2026-04-23
2,How to Better Regulate Your Emotions | Dr. Mar...,117628,3004,2026-04-20
3,Understand & Improve Memory Using Science-Base...,108021,3623,2026-04-16
4,How Women Can Improve Their Fertility & Hormon...,63709,1369,2026-04-13
...,...,...,...,...
476,"How to Defeat Jet Lag, Shift Work & Sleeplessness",570678,14530,2021-01-25
477,"Using Science to Optimize Sleep, Learning & Me...",1404975,37943,2021-01-18
478,Master Your Sleep & Be More Alert When Awake,4268927,117538,2021-01-11
479,How Your Brain Works & Changes,2007251,66227,2021-01-04
480,Welcome to the Huberman Lab Podcast,1425418,20739,2020-12-23

In [17]:
# On transforme le DataFrame (df) en un fichier appelé 'data_youtube.json'
# orient='records' permet d'avoir une liste de dictionnaires (le format standard)
# indent=4 rend le fichier lisible par un humain (plus joli)
df.to_json('df.json', orient='records', indent=4)

print("✅ Ton fichier JSON a été créé avec succès !")

✅ Ton fichier JSON a été créé avec succès !

In [18]:
import pandas as pd  # <--- CETTE LIGNE EST LA CLÉ !

# 1. On transforme la liste en tableau (DataFrame)
df = pd.DataFrame(infos_videos_completes)

# 2. On nettoie la date
df['Date'] = pd.to_datetime(df['Date']).dt.date

# 3. On affiche le résultat pour vérifier
print(f"✅ Extraction réussie de {len(df)} vidéos.")
display(df.head()) 

# 4. On crée le fichier JSON (Maintenant ça va marcher !)
df.to_json('data_youtube.json', orient='records', indent=4)
print("🚀 Ton fichier 'data_youtube.json' est prêt !")

✅ Extraction réussie de 481 vidéos.

,Titre,Vues,Likes,Date
0,"Male Roles, Obligations and Options for Buildi...",66194,2094,2026-04-27
1,"Essentials: The Neuroscience of Speech, Langua...",33783,709,2026-04-23
2,How to Better Regulate Your Emotions | Dr. Mar...,117628,3004,2026-04-20
3,Understand & Improve Memory Using Science-Base...,108021,3623,2026-04-16
4,How Women Can Improve Their Fertility & Hormon...,63709,1369,2026-04-13

🚀 Ton fichier 'data_youtube.json' est prêt !

In [19]:
infos_videos_completes = []

for i in range(0, len(all_video_ids), 50):
    groupe_ids = ",".join(all_video_ids[i:i+50])
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={groupe_ids}&key={API_KEY}"
    reponse = requests.get(url).json()
    
    for video in reponse.get('items', []):
        infos_videos_completes.append({
            'Video_ID': video['id'],  # <--- ON AJOUTE CETTE LIGNE
            'Titre': video['snippet']['title'],
            'Vues': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Date': video['snippet']['publishedAt']
        })

# On recrée le DataFrame et le JSON
import pandas as pd
df = pd.DataFrame(infos_videos_completes)
df['Date'] = pd.to_datetime(df['Date']).dt.date

# Sauvegarde en JSON
df.to_json('data_youtube_complet.json', orient='records', indent=4)

print("✅ Terminé ! L'ID est maintenant inclus dans le tableau et le fichier JSON.")
display(df.head())

✅ Terminé ! L'ID est maintenant inclus dans le tableau et le fichier JSON.

,Video_ID,Titre,Vues,Likes,Date
0,sQcS6f2qYoQ,"Male Roles, Obligations and Options for Buildi...",66194,2094,2026-04-27
1,3bnLgOxHMB8,"Essentials: The Neuroscience of Speech, Langua...",33783,709,2026-04-23
2,FBgM7jndkLQ,How to Better Regulate Your Emotions | Dr. Mar...,117628,3004,2026-04-20
3,U6dnOVth7-I,Understand & Improve Memory Using Science-Base...,108021,3623,2026-04-16
4,RTPNJgHeZBI,How Women Can Improve Their Fertility & Hormon...,63709,1369,2026-04-13

In [20]:
import pandas as pd

# 1. On repart de ta liste vide
infos_videos_completes = []

# 2. La boucle qui parcourt tes IDs par lots de 50
for i in range(0, len(all_video_ids), 50):
    groupe_ids = ",".join(all_video_ids[i:i+50])
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id={groupe_ids}&key={API_KEY}"
    reponse = requests.get(url).json()
    
    # 3. Pour chaque vidéo, on récupère l'ID ET les détails
    for video in reponse.get('items', []):
        infos_videos_completes.append({
            'ID_Video': video['id'],  # <-- C'est ici qu'on ajoute l'ID
            'Titre': video['snippet']['title'],
            'Vues': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Date': video['snippet']['publishedAt']
        })

# 4. On transforme tout ça en DataFrame (Tableau)
df = pd.DataFrame(infos_videos_completes)
df['Date'] = pd.to_datetime(df['Date']).dt.date

# 5. On exporte le nouveau fichier JSON
df.to_json('data_youtube_final.json', orient='records', indent=4)

print("✅ Succès ! Le fichier 'data_youtube_final.json' contient maintenant les IDs.")
display(df.head())

✅ Succès ! Le fichier 'data_youtube_final.json' contient maintenant les IDs.

,ID_Video,Titre,Vues,Likes,Date
0,sQcS6f2qYoQ,"Male Roles, Obligations and Options for Buildi...",66194,2094,2026-04-27
1,3bnLgOxHMB8,"Essentials: The Neuroscience of Speech, Langua...",33783,709,2026-04-23
2,FBgM7jndkLQ,How to Better Regulate Your Emotions | Dr. Mar...,117628,3004,2026-04-20
3,U6dnOVth7-I,Understand & Improve Memory Using Science-Base...,108021,3623,2026-04-16
4,RTPNJgHeZBI,How Women Can Improve Their Fertility & Hormon...,63709,1369,2026-04-13

In [22]:
import isodate # Si tu as une erreur, fais : pip install isodate
import pandas as pd

infos_videos_completes = []

for i in range(0, len(all_video_ids), 50):
    groupe_ids = ",".join(all_video_ids[i:i+50])
    # Ajout de 'contentDetails' pour avoir la durée
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics,contentDetails&id={groupe_ids}&key={API_KEY}"
    reponse = requests.get(url).json()
    
    for video in reponse.get('items', []):
        # 1. On récupère la durée brute (ex: PT5M30S)
        duree_iso = video['contentDetails']['duration']
        
        # 2. On transforme cette durée en secondes réelles
        duree_secondes = isodate.parse_duration(duree_iso).total_seconds()
        
        # 3. On crée la règle : Short ou Vidéo longue
        est_short = "Oui" if duree_secondes <= 60 else "Non"
        
        infos_videos_completes.append({
            'ID_Video': video['id'],
            'Titre': video['snippet']['title'],
            'Vues': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Duree_Secondes': int(duree_secondes),
            'Est_Short': est_short,
            'Date': video['snippet']['publishedAt']
        })

# Transformation en tableau
df = pd.DataFrame(infos_videos_completes)
df['Date'] = pd.to_datetime(df['Date']).dt.date

# Sauvegarde du nouveau JSON
df.to_json('data_youtube_shorts.json', orient='records', indent=4)

print("✅ Analyse terminée ! Les colonnes 'Duree_Secondes' et 'Est_Short' sont ajoutées.")
display(df.head(10))

✅ Analyse terminée ! Les colonnes 'Duree_Secondes' et 'Est_Short' sont ajoutées.

,ID_Video,Titre,Vues,Likes,Duree_Secondes,Est_Short,Date
0,sQcS6f2qYoQ,"Male Roles, Obligations and Options for Buildi...",66194,2094,9352,Non,2026-04-27
1,3bnLgOxHMB8,"Essentials: The Neuroscience of Speech, Langua...",33783,709,2128,Non,2026-04-23
2,FBgM7jndkLQ,How to Better Regulate Your Emotions | Dr. Mar...,117634,3004,8858,Non,2026-04-20
3,U6dnOVth7-I,Understand & Improve Memory Using Science-Base...,108021,3623,2150,Non,2026-04-16
4,RTPNJgHeZBI,How Women Can Improve Their Fertility & Hormon...,63709,1369,9363,Non,2026-04-13
5,xZ4I2aE8zQA,"Essentials: The Biology of Aggression, Mating ...",43337,917,2048,Non,2026-04-09
6,Tmw2dW0a9DY,Cultivating Awe & Emotional Connection in Dail...,83286,1742,8420,Non,2026-04-06
7,0VSOoMuStvg,"Essentials: How to Build Strength, Muscle Size...",123047,2868,2066,Non,2026-04-02
8,6-mEiwe2NhE,How Hormones Shape Sexual Orientation & Behavi...,136594,3409,7878,Non,2026-03-30
9,hnzrPKvRBD8,Using Salt to Optimize Mental & Physical Perfo...,94486,2764,2034,Non,2026-03-26

In [23]:
import isodate 
import pandas as pd

infos_videos_completes = []

for i in range(0, len(all_video_ids), 50):
    groupe_ids = ",".join(all_video_ids[i:i+50])
    # On garde snippet, statistics et contentDetails pour avoir toutes les infos
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics,contentDetails&id={groupe_ids}&key={API_KEY}"
    reponse = requests.get(url).json()
    
    for video in reponse.get('items', []):
        # Calcul de la durée
        duree_iso = video['contentDetails']['duration']
        duree_secondes = isodate.parse_duration(duree_iso).total_seconds()
        
        # Détermination si c'est un Short
        est_short = "Oui" if duree_secondes <= 60 else "Non"
        
        # Ajout des informations dans notre liste
        infos_videos_completes.append({
            'ID_Video': video['id'],
            'Titre': video['snippet']['title'],
            'Vues': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Commentaires': int(video['statistics'].get('commentCount', 0)), # <-- NOUVEAU
            'Duree_Secondes': int(duree_secondes),
            'Est_Short': est_short,
            'Date': video['snippet']['publishedAt']
        })

# Transformation en DataFrame
df = pd.DataFrame(infos_videos_completes)
df['Date'] = pd.to_datetime(df['Date']).dt.date

# Sauvegarde en JSON
df.to_json('data_youtube_final_complet.json', orient='records', indent=4)

print("✅ Mission accomplie ! Le nombre de commentaires est maintenant inclus.")
display(df.head(10))

✅ Mission accomplie ! Le nombre de commentaires est maintenant inclus.

,ID_Video,Titre,Vues,Likes,Commentaires,Duree_Secondes,Est_Short,Date
0,sQcS6f2qYoQ,"Male Roles, Obligations and Options for Buildi...",66218,2092,332,9352,Non,2026-04-27
1,3bnLgOxHMB8,"Essentials: The Neuroscience of Speech, Langua...",33789,709,64,2128,Non,2026-04-23
2,FBgM7jndkLQ,How to Better Regulate Your Emotions | Dr. Mar...,117636,3004,217,8858,Non,2026-04-20
3,U6dnOVth7-I,Understand & Improve Memory Using Science-Base...,108027,3623,147,2150,Non,2026-04-16
4,RTPNJgHeZBI,How Women Can Improve Their Fertility & Hormon...,63709,1369,140,9363,Non,2026-04-13
5,xZ4I2aE8zQA,"Essentials: The Biology of Aggression, Mating ...",43337,917,95,2048,Non,2026-04-09
6,Tmw2dW0a9DY,Cultivating Awe & Emotional Connection in Dail...,83292,1741,197,8420,Non,2026-04-06
7,0VSOoMuStvg,"Essentials: How to Build Strength, Muscle Size...",123049,2868,111,2066,Non,2026-04-02
8,6-mEiwe2NhE,How Hormones Shape Sexual Orientation & Behavi...,136596,3409,560,7878,Non,2026-03-30
9,hnzrPKvRBD8,Using Salt to Optimize Mental & Physical Perfo...,94486,2764,213,2034,Non,2026-03-26